name: Git Tag Semver

on:
  workflow_call:
    inputs:
      version:
        type: string
        description: |
          The semantic version bump to apply. One of "patch", "minor", or "major".
        required: true
      sha:
        type: string
        description: The commit SHA to tag.
        required: false
        default: ${{ github.sha }}
      skip:
        type: boolean
        description: Whether to skip the workflow or not.
        required: false
        default: false
    secrets:
      github-token:
        description: The GitHub token utilized to push the tags.
        required: false
    outputs:
      tags:
        description: A stringified JSON array of the triplets of tags upserted.
        value: ${{ jobs.git-tag-semver.outputs.tags }}

permissions:
  contents: write
  pull-requests: write

env:
  status-report-action-repository: infrastructure-blocks/git-tag-semver-workflow

jobs:
<<<<<<< HEAD
  git-tag-semver:
    if: ${{ !inputs.skip }}
=======
  example-job:
>>>>>>> template/master
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    outputs:
      tags: ${{ steps.git-tag.outputs.tags }}
    steps:
<<<<<<< HEAD
      - id: variables
=======
      # This condition should be on every step.
      - if: ${{ !inputs.skip }}
        id: example-step
        name: Example step
        env:
          BIG_SECRET: ${{ secrets.example-secret }}
>>>>>>> template/master
        run: |
          if test -n "${{ secrets.github-token }}"; then
            echo "token=${{ secrets.github-token }}" >> "${GITHUB_OUTPUT}"
          else
            echo "token=${{ github.token }}" >> "${GITHUB_OUTPUT}"
          fi
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}
          token: ${{ steps.variables.outputs.token }}
      - id: git-tag
        uses: infrastructure-blocks/git-tag-semver-action@v1
        with:
          version: ${{ inputs.version }}
      - if: ${{ always() }}
        id: get-current-pr
        uses: infrastructure-blocks/get-current-pull-request-action@v1
        continue-on-error: true
        with:
          sha: ${{ inputs.sha }}
      - if: ${{ steps.get-current-pr.outputs.id != '' }}
        uses: infrastructure-blocks/status-report-action@v1
        with:
          issue-number: ${{ steps.get-current-pr.outputs.number }}
          body: |
            :rocket: **Success**: Commit ${{ inputs.sha }} tagged!
            Tags:
              - [${{ fromJson(steps.git-tag.outputs.tags)[0] }}](https://github.com/${{ github.repository }}/releases/tag/${{ fromJson(steps.git-tag.outputs.tags)[0] }})
              - [${{ fromJson(steps.git-tag.outputs.tags)[1] }}](https://github.com/${{ github.repository }}/releases/tag/${{ fromJson(steps.git-tag.outputs.tags)[1] }})
              - [${{ fromJson(steps.git-tag.outputs.tags)[2] }}](https://github.com/${{ github.repository }}/releases/tag/${{ fromJson(steps.git-tag.outputs.tags)[2] }})
      - if: ${{ failure() && steps.get-current-pr.outputs.id != '' }}
        uses: infrastructure-blocks/status-report-action@v1
        with:
          issue-number: ${{ steps.get-current-pr.outputs.number }}
          body: |
            :boom: **Error**: Tagging sha ${{ inputs.sha }} with version bump `${{ inputs.version }}`
            See [action logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ github.job }})
